version: '3.7'
services:
  archiva:
    image: edsonmoreirajr/archiva-docker-arm
    ports: 
     - 8082:8080
    environment:
      SMTP_HOST: smtp
      SMTP_PORT: 1025
    networks:
      - container
  smtp:
    image: mailhog/mailhog:latest
    ports: 
      - 8025:8025
    networks:
      - container
networks:
  container:
